
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
index:
    path: /blog/index
    controller: App\Controller\BlogController::index
contact:
    path: /blog/contact
    controller: App\Controller\BlogController::contact
login:
    path: /blog/login
    controller: App\Controller\BlogController::login
list:
    path: /blog/list/{page}
    controller: App\Controller\BlogController::list
view:
    path: /blog/view
    controller: App\Controller\BlogController::view